module.exports = [
	{
		title: 'Silverlight 4 in Action, Revised Edition',
		isbn: '1935182374',
		pageCount: 425,
		publishedDate: { $date: '2010-10-04T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/pbrown.jpg',
		shortDescription:
			"Silverlight in Action, Revised Edition is a comprehensive guide to Silverlight, taking you from Hello World through the techniques you'll need to build sophisticated rich web apps. This new edition covers all the new features added in the latest versions of Silverlight, Visual Studio, and Expression Blend, along with the best practices emerging in the Silverlight community. With more than 50% new content, you'll take a mind-expanding trip through the technology, features, and techniques required to build applications ranging from media, to custom experiences, to business applications to games.",
		longDescription:
			"Anyone who has gotten a taste of what it can do knows that Silverlight represents an entirely new level of rich web interface technology for Microsoft developers. With Silverlight, developers can use JavaScript, C#, and other languages to build user-friendly, interactive, and visually-dazzling web applications that work in most major browsers.    Silverlight in Action, Revised Edition is a comprehensive guide to Silverlight, taking you from Hello World through the techniques you'll need to build sophisticated rich web apps. This new edition covers all the new features added in the latest versions of Silverlight, Visual Studio, and Expression Blend, along with the best practices emerging in the Silverlight community. With more than 50% new content, you'll take a mind-expanding trip through the technology, features, and techniques required to build applications ranging from media, to custom experiences, to business applications to games.    Beyond the fundamentals, you'll find numerous practical examples of important patterns like the ViewModel (or MVVM) pattern, and effective practices for developing real-world applications. You'll delve into the underlying object model and what makes Silverlight tick. Business application developers will appreciate the coverage of the exciting new.NET RIA Services. Combined with advanced binding and validation techniques, they help you visualize how to make your application development super productive and your architecture flexible enough to implement solutions in any problem domain.    Silverlight in Action, Revised Edition devotes extensive coverage to flexible layout components, the extensible control model, the communication framework, and the data-binding features-all cornerstones of software development. You'll master Silverlight's rich media and vivid graphical and animation features. The closing chapters include a variety of Silverlight deployment and customization scenarios.    Finally, Silverlight in Action, Revised Edition doesn't leave you in the dark when it comes to testing and debugging your applications. Techniques, tools, and patterns to support testable Silverlight applications are woven throughout the chapters, with additional dedicated content on the specifics of testing and debugging in Silverlight.",
		status: 'PUBLISH',
		authors: ['Pete Brown'],
		categories: ['Microsoft .NET'],
	},
	{
		title: 'Spring in Practice',
		isbn: '1935182056',
		pageCount: 600,
		publishedDate: { $date: '2013-05-09T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/wheeler.jpg',
		shortDescription:
			"Spring in Practice diverges from other cookbooks because it presents the background you need to understand the domain in which a solution applies before it offers the specific steps to solve the problem. You're never left with the feeling that you understand the answer, but find the question irrelevant. You can put the book to immediate use even if you don't have deep knowledge of every part of Spring Framework.",
		longDescription:
			"For enterprise Java developers, Spring Framework provides remarkable improvements in developer productivity, runtime performance, and overall application quality. Its unique blend of a complete, lightweight container that allows you to build a complex application from loosely-coupled POJOs and a set of easily understood abstractions that simplify construction, testing, and deployment make Spring both powerful and easy-to-use   a hard-to-beat combination. With this power comes the potential for a wide range of uses in both common and not-so-common scenarios. That's where Spring in Practice comes in.    Unlike the many books that teach you what Spring is, Spring in Practice shows you how to tackle the challenges you face when you build Spring-based applications. The book empowers software developers to solve concrete business problems \"the Spring way\" by mapping application-level issues to Spring-centric solutions.    Spring in Practice diverges from other cookbooks because it presents the background you need to understand the domain in which a solution applies before it offers the specific steps to solve the problem. You're never left with the feeling that you understand the answer, but find the question irrelevant. You can put the book to immediate use even if you don't have deep knowledge of every part of Spring Framework.    The book divides into three main parts. In Part 1, you'll get a rapid overview of Spring Framework   enough to get you started if you're new and a great refresher for readers who already have a few Spring cycles. Part 2 provides techniques that are likely to be useful no matter what type of application you're building. You'll find discussions of topics like user accounts, security, site navigation, and application diagnosis.    Part 3 provides domain-specific recipes. Here, you'll find practical solutions to realistic and interesting business problems. For example, this part discusses Spring-based approaches for ecommerce, lead generation, and CRM.    There are several recurring themes throughout Spring in Practice, including Spring MVC, Hibernate, and transactions. Each recipe is an opportunity to highlight something new or interesting about Spring, and to focus on that concept in detail.    This book assumes you have a good foundation in Java and Java EE. Prior exposure to Spring Framework is helpful, but not required.",
		status: 'PUBLISH',
		authors: ['Willie Wheeler with Joshua White'],
		categories: ['Java', 'Software Development'],
	},
	{
		title: 'Java 2 Micro Edition',
		isbn: '1930110332',
		pageCount: 504,
		publishedDate: { $date: '2002-03-01T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/white.jpg',
		longDescription:
			'Java2, Micro Edition (J2ME) is a technology defined by many specifications. These specifications help J2ME address the diverse needs of this wide spectrum of consumer products. This guide describes the architecture of J2ME and demonstrates the various specifications for programming Java applications.    Through the use of a tutorial application and various programming examples, the common elements of most applications, namely user interface, event handling, data storage, networking, and input/output are examined. Also covered are design considerations when building software for resource-constrained devices as well as J2ME competition and associated technologies in these devices.    Tutorial and API example application source code downloads will be available from this site.',
		status: 'PUBLISH',
		authors: ['James P. White', 'David A. Hemphill'],
		categories: ['Java', 'Internet'],
	},
	{
		title: 'SharePoint 2010 Workflows in Action',
		isbn: '1935182714',
		pageCount: 360,
		publishedDate: { $date: '2011-02-07T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/wicklund.jpg',
		shortDescription:
			'SharePoint 2010 Workflows in Action is a hands-on guide for workflow application development in SharePoint. Power users are introduced to the simplicity of building and integrating workflows using SharePoint Designer, Visio, InfoPath, and Office. Developers will learn to build custom processes and use external data sources. They will learn about state machine workflows, ASP.NET forms, event handlers, and much more. This book requires no previous experience with workflow app development. ',
		longDescription:
			'You can use SharePoint 2010 workflows to transform a set of business processes into working SharePoint applications. For that task, a power user gets prepackaged workflows, wizards, and design tools, and a programmer benefits from Visual Studio to handle advanced workflow requirements.    SharePoint 2010 Workflows in Action is a hands-on guide for workflow application development in SharePoint. Power users are introduced to the simplicity of building and integrating workflows using SharePoint Designer, Visio, InfoPath, and Office. Developers will learn to build custom processes and use external data sources. They will learn about state machine workflows, ASP.NET forms, event handlers, and much more. This book requires no previous experience with workflow app development. ',
		status: 'PUBLISH',
		authors: ['Phil Wicklund'],
		categories: ['Microsoft .NET'],
	},
	{
		title: 'SharePoint 2010 Web Parts in Action',
		isbn: '1935182773',
		pageCount: 448,
		publishedDate: { $date: '2011-04-24T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/wilen.jpg',
		shortDescription:
			"SharePoint 2010 Web Parts in Action is a comprehensive guide to deploying, customizing, and creating Web Parts. Countless examples walk you through everything from design, to development, deployment, troubleshooting, and upgrading. Because Web Parts are ASP.NET controls, you'll learn to use Visual Studio 2010 to extend existing Web Parts and to build custom components from scratch. ",
		longDescription:
			"If you look at a SharePoint application you'll find that most of its active components are Web Parts. SharePoint 2010 includes dozens of prebuilt Web Parts that you can use. It also provides an API that lets you build custom Web Parts using C# or VB.NET.    SharePoint 2010 Web Parts in Action is a comprehensive guide to deploying, customizing, and creating Web Parts. Countless examples walk you through everything from design, to development, deployment, troubleshooting, and upgrading. Because Web Parts are ASP.NET controls, you'll learn to use Visual Studio 2010 to extend existing Web Parts and to build custom components from scratch. ",
		status: 'PUBLISH',
		authors: ['Wictor Wilén'],
		categories: ['Microsoft .NET'],
	},
	{
		title: 'C++ Concurrency in Action',
		isbn: '1933988770',
		pageCount: 325,
		publishedDate: { $date: '2012-02-24T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/williams.jpg',
		shortDescription:
			'C++ Concurrency in Action is the first book to show you how to take advantage of the new C++ Standard and TR2 to write robust multi-threaded applications in C++.',
		longDescription:
			"It seems like we're all being asked to multi-task more than ever   and our computers are no exception to this trend. Multiple processors with multiple cores running multiple threads is quickly becoming the norm. C++ developers will have to master the principles, techniques, and new language features supporting concurrency to stay ahead of the curve.    With the new C++ Standard and Technical Report 2 (TR2), multi-threading is coming to C++ in a big way. There is a new memory model with support for multiple threads, along with a new multi-threading support library featuring low-level atomic operations, as well as basic thread launching and synchronization facilities. TR2 will provide higher-level synchronization facilities that allow for a much greater level of abstraction, and make programming multi-threaded applications simpler and safer.    C++ Concurrency in Action is the first book to show you how to take advantage of the new C++ Standard and TR2 to write robust multi-threaded applications in C++.    As a guide and reference to the new concurrency features in the upcoming C++ Standard and TR, this book is invaluable for existing programmers familiar with writing multi-threaded code in C++ using platform-specific APIs, or in other languages, as well as C++ programmers who have never written multi-threaded code before.    If you're a programmer accustomed to writing single-threaded applications, C++ Concurrency in Action will show you how to write your new parallel algorithm in C++. You'll learn to avoid many of the pitfalls associated with writing multi-threaded applications. You can also use this book to quickly transfer your platform-specific knowledge to the new Standard C++ threading library, enabling you to use a single API on both systems and simplify your code.",
		status: 'PUBLISH',
		authors: ['Anthony Williams'],
		categories: ['Microsoft .NET'],
	},
	{
		title: 'Java Servlets by Example',
		isbn: '188477766X',
		pageCount: 550,
		publishedDate: { $date: '2002-12-01T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/williamson.jpg',
		longDescription:
			"Although CGI scripts provide 80% of today's server side processing, they are slow, inefficient, and memory-hungry. A new species is evolving to take their place, one which is lean, fast, portable, and easy to maintain: Java servlets.    Servlets are not merely an alternative to CGI, for they can do much more. Servlets have opened the door to a world of client/server applications that would have been too difficult or too time-consuming to consider before.    Java Servlets: By Example takes the reader into the world of servlets, moving example by example from the simple to the complex. An early chapter explains the simple HTML form processing through servlets. A later chapter shows how to connect a Java applet to a servlet, which is itself connected to a database.    Java Servlets: By Example is full of real-world, ready-to-run example code. Each chapter deals with a new problem and takes the reader through a series of servlet-based solutions. However, the book is detailed enough that it may also serve as a reference for the developer.",
		status: 'PUBLISH',
		authors: ['Alan R. Williamson'],
		categories: ['Java', 'Internet'],
	},
	{
		title: 'XML Programming with VB and ASP',
		isbn: '1884777872',
		pageCount: 320,
		publishedDate: { $date: '1999-12-01T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/wilson.jpg',
		longDescription:
			"Here's a book that shows you when and how to use XML from both a programming and business perspective. Laden with source code, XML Programming with VB and ASP helps you build solutions that are flexible, future-proof, and self-describing. It will help you apply XML concepts between the client and the server and the server and data objects or data services.    Finally, you have everything a VB and ASP developer needs to keep up with the explosive growth of XML.",
		status: 'PUBLISH',
		authors: ['Mark Wilson', 'Tracey Wilson'],
		categories: ['XML', 'Internet'],
	},
	{
		title: 'Oracle8i Database Administration',
		isbn: '1884777783',
		pageCount: 543,
		publishedDate: { $date: '1999-11-01T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/yuhanna.jpg',
		longDescription:
			"Databases are growing larger, and the use of distributed databases is on the rise. Oracle8i Database Administration addresses some of the most common yet complex issues that are faced by DBAs around the world.    Oracle has the largest market share in Database Management software and is the world's second largest software company. This book is designed for for Oracle Database administrators and others who are involved in planning, programming, administration, and implementation of Oracle8 Databases.    Although this book targets intermediate and advanced database administrators, it can also be an invaluable resource to entry-level DBAs, designers and developers, project managers, system administrators, data warehousing professionals or anyone interested in Oracle.    Oracle8i Database Administration uses a Q&A approach that provides in-depth technical solutions. The questions in this book have been compiled from many sources including Oracle forums, the Internet, and the author's personal experiences. The book also examines features that are new in Oracle8.",
		status: 'PUBLISH',
		authors: ['Noel Yuhanna'],
		categories: ['Client-Server', 'Networking'],
	},
	{
		title: 'The Engaging Web',
		isbn: '9781935182078',
		pageCount: 325,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/zichermann.jpg',
		shortDescription:
			"The Engaging Web: How Fun and Games Improve Your Site shows web developers how to incorporate games into websites. This book will help you decode the possibilities and provide a series of proven and tangible strategies that any web developer, producer, or product manager can use to implement games in their website. Whether you're looking to make games the centerpiece of your site, an added-value feature, or you just want to engage and excite your users, The Engaging Web will help you develop a strategy that harnesses the power of games.",
		longDescription:
			"Games are the fastest-growing and stickiest form of entertainment. For a website, games offer powerful potential to acquire new users, build engagement, and enhance revenue. Implementing games in a website can be complicated, though. There are hundreds of technical and process options to choose from, and the landscape is constantly shifting.    The Engaging Web: How Fun and Games Improve Your Site shows web developers how to incorporate games into websites. This book will help you decode the possibilities and provide a series of proven and tangible strategies that any web developer, producer, or product manager can use to implement games in their website. Whether you're looking to make games the centerpiece of your site, an added-value feature, or you just want to engage and excite your users, The Engaging Web will help you develop a strategy that harnesses the power of games.    Through this book, you will take away an in-depth understanding of the current state of the art in game and web planning and integration methodologies. It begins by presenting an understanding of basic \"funware\" principles - or how non-designers can use games to further business objectives. Powerful funware designs like frequent flyer programs, casino games, and leaderboard/ladders will be deconstructed and componentized so that you can leverage their strengths for your specific site and business objectives.    You'll then investigate the three basic recipes for melding games with the web, and look at specific examples of integration approaches that have been successfully deployed across various industries. Finally, you'll examine social networking considerations and look at code examples.    Whether you're building a business or consumer site, games and funware design can be a powerful weapon in your battle for user engagement, stickiness, and revenue. The Engaging Web is the field guide that gives you the best tactics, techniques, and strategies for winning the war.    WHAT'S INSIDE        * Understanding funware and game design      * Principal funware designs: casinos frequent flyer programs, leaderboards      * Matching games to your business objectives      * Recipes for implementing games on your site      * Games, social networking and you      * Code examples",
		status: 'MEAP',
		authors: ['Gabe Zichermann', 'Chris Cunningham'],
		categories: ['Web Development'],
	},
	{
		title: 'Enterprise OSGi In Action',
		isbn: '1617290130',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/cummins.jpg',
		status: 'PUBLISH',
		authors: ['Holly Cummins', 'Timothy Ward'],
		categories: [],
	},
	{
		title: 'Ext JS in Action, Second Edition',
		isbn: '1617290327',
		pageCount: 0,
		publishedDate: { $date: '2014-02-04T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/garcia3.jpg',
		status: 'PUBLISH',
		authors: ['Jesus Garcia', 'Grgur Grisogono', '', 'Jacob K. Andresen'],
		categories: [],
	},
	{
		title: 'Android in Action, Third Edition',
		isbn: '1617290505',
		pageCount: 0,
		publishedDate: { $date: '2011-11-15T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/ableson3.jpg',
		status: 'PUBLISH',
		authors: [
			'W. Frank Ableson',
			'Robi Sen',
			'Chris King',
			'C. Enrique Ortiz',
		],
		categories: [],
	},
	{
		title: 'Arduino in Action',
		isbn: '1617290246',
		pageCount: 300,
		publishedDate: { $date: '2013-05-30T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/mevans.jpg',
		shortDescription:
			'Arduino in Action is a hands-on guide to prototyping and building electronics using the Arduino platform. Suitable for beginners and advanced users, this easy to follow book begins with the basics and systematically guides you through projects ranging from your first blinking LED through connecting Arduino to devices like game controllers or your iPhone.',
		longDescription:
			"Whether you want to build an autonomous robot, automate your home electronics, or just automatically tweet when the bread is ready, you can do it with Arduino. Arduino is an inexpensive, easy-to-use, open source hardware and software platform. It supports a mind-boggling array of sensors and components that you can use to build nearly anything you can imagine.\n\nArduino in Action is a hands-on guide to prototyping and building electronics using the Arduino platform. Suitable for beginners and advanced users, this easy to follow book begins with the basics and systematically guides you through projects ranging from your first blinking LED through connecting Arduino to devices like game controllers or your iPhone.\n\nYou'll start at the very beginning: unpacking your first Arduino board, connecting it to a PC, and using the programming environment to make something happen. You'll follow progressively more complex examples as you connect your Arduino to motors, LCD displays, Wi-Fi, GPS, and Bluetooth. You'll explore a variety of input output sensors, including ultrasound, infrared, and light, along with how to use them for tasks like robotic obstacle avoidance.",
		status: 'PUBLISH',
		authors: ['Martin Evans', 'Joshua Noble', '', 'Jordan Hochenbaum'],
		categories: [],
	},
	{
		title: 'Node.js in Action',
		isbn: '1617290572',
		pageCount: 300,
		publishedDate: { $date: '2013-10-15T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/cantelon.jpg',
		shortDescription:
			"Node.js in Action is an example-driven tutorial that starts at square one and guides you through all the features, techniques, and concepts you'll need to build production-quality Node applications. You'll start by learning how to set up your Node development environment, including loading the community-created extensions. Next, you'll run several simple demonstration programs where you'll learn the basics of a few common types of Node applications. Then you'll dive into asynchronous programming, a model Node leverages to lessen application bottlenecks.",
		longDescription:
			"JavaScript on the server? Yep. Node.js is an elegant server-side JavaScript development environment perfect for scalable, high-performance web applications. With Node you access HTTP and TCP/IP functionality through a minimalist server-side Javascript interface. It supports an asynchronous programming model that enables the web server to more easily do more than one thing at a time, a key requirement for real-time applications such as chat, online games, and live statistics. And since it's JavaScript, you'll use the same language throughout your entire application.\n\nNode.js in Action is an example-driven tutorial that starts at square one and guides you through all the features, techniques, and concepts you'll need to build production-quality Node applications. You'll start by learning how to set up your Node development environment, including loading the community-created extensions. Next, you'll run several simple demonstration programs where you'll learn the basics of a few common types of Node applications. Then you'll dive into asynchronous programming, a model Node leverages to lessen application bottlenecks.\n\nWith the basics under your belt, you're ready to start building serious web applications using Node's HTTP API. You'll explore data storage, application deployment, and output templating, and you'll discover community frameworks that make web development easier and faster. Along the way, you'll learn to interact with the filesystem and to create non-HTTP applications, such as TCP/IP servers and command-line tools.\n\nMuch of the Node ecosystem is open source, so this book will show you how the community works and how you can contribute. You'll learn about the NPM Repository, where most community extensions reside, and you'll learn how to publish your own extensions. In addition, the book outlines online resources for getting help with any stumbling blocks you run into during your journey as a Node developer.\nWHAT'S INSIDE",
		status: 'PUBLISH',
		authors: [
			'Mike Cantelon',
			'Marc Harter',
			'T.J. Holowaychuk',
			'',
			'Nathan Rajlich',
		],
		categories: ['Web Development'],
	},
	{
		title: 'Third-Party JavaScript ',
		isbn: '1617290548',
		pageCount: 0,
		publishedDate: { $date: '2013-03-11T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/vinegar.jpg',
		status: 'PUBLISH',
		authors: ['Ben Vinegar', 'Anton Kovalyov'],
		categories: [],
	},
	{
		title: 'Multimedia Computing',
		isbn: '020152029X',
		pageCount: 0,
		publishedDate: { $date: '1993-09-01T00:00:00.000-0700' },
		status: 'PUBLISH',
		authors: ['Matthew E. Hodges'],
		categories: [],
	},
	{
		title: 'Web Development with JavaServer Pages',
		isbn: '1884777996',
		pageCount: 0,
		publishedDate: { $date: '2000-05-15T00:00:00.000-0700' },
		status: 'PUBLISH',
		authors: ['Duane K. Fields', 'Mark A. Kolb'],
		categories: [],
	},
	{
		title: 'Up to Speed with Swing',
		isbn: '1884777643',
		pageCount: 0,
		publishedDate: { $date: '1998-05-01T00:00:00.000-0700' },
		status: 'PUBLISH',
		authors: ['Steven J. Gutz'],
		categories: [],
	},
	{
		title: "Manager's Guide to Open Source",
		isbn: '193239429X',
		pageCount: 0,
		publishedDate: { $date: '2004-10-01T00:00:00.000-0700' },
		status: 'PUBLISH',
		authors: ['Maria Winslow'],
		categories: [],
	},
	{
		title: 'Programming Web Services with Java',
		isbn: '1930110421',
		pageCount: 0,
		publishedDate: { $date: '2002-10-01T00:00:00.000-0700' },
		status: 'PUBLISH',
		authors: ['Ajamu A. Wesley'],
		categories: [],
	},
	{
		title: 'TCP/IP Programming for OS/2',
		isbn: '132612496',
		pageCount: 0,
		publishedDate: { $date: '1996-04-23T00:00:00.000-0700' },
		status: 'PUBLISH',
		authors: ['Steven J. Gutz'],
		categories: [],
	},
	{
		title: 'SCWCD Exam Study Kit',
		isbn: '1930110596',
		pageCount: 0,
		publishedDate: { $date: '2002-07-01T00:00:00.000-0700' },
		status: 'PUBLISH',
		authors: ['Hanumant Deshmukh', 'Jignesh Malavia'],
		categories: [],
	},
	{
		title: 'Unit Testing in C++',
		isbn: '1617290386',
		pageCount: 0,
		status: 'PUBLISH',
		authors: ['Bruce Trask', 'Angel Roman'],
		categories: [],
	},
	{
		title: 'Big Data',
		isbn: '1617290343',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/marz.jpg',
		status: 'MEAP',
		authors: ['Nathan Marz', 'James Warren'],
		categories: [],
	},
	{
		title: 'CoffeeScript in Action',
		isbn: '1617290629',
		pageCount: 0,
		publishedDate: { $date: '2014-05-09T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/lee.jpg',
		status: 'PUBLISH',
		authors: ['Patrick Lee'],
		categories: [],
	},
	{
		title: 'SQL Server MVP Deep Dives, Volume 2',
		isbn: '1617290475',
		pageCount: 750,
		publishedDate: { $date: '2011-10-13T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/delaney.jpg',
		status: 'PUBLISH',
		authors: [
			'Kalen Delaney',
			'Louis Davidson',
			'Greg Low',
			'Brad McGehee',
			'Paul Nielsen',
			'Paul Randal',
			'',
			'Kimberly Tripp',
		],
		categories: [],
	},
	{
		title: 'HTML5 in Action',
		isbn: '1617290491',
		pageCount: 375,
		publishedDate: { $date: '2014-02-10T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/crowther2.jpg',
		shortDescription:
			"HTML5 In Action provides a complete introduction to web development using HTML5. You'll explore every aspect of the HTML5 specification through real-world examples and code samples. It's much more than just a specification reference, though. It lives up to the name HTML5 in Action by giving you the practical, hands-on guidance you'll need to use key features.",
		longDescription:
			"The Web is buzzing about HTML5. What is it? Which browsers support what features? When the specification will be complete? HTML5, along with supporting technologies like CSS3, SVG, and JavaScript, gives web developers powerful new features like local storage, better audio and video support, and standards-driven mobile application development. And it's ready to use now, with browser support from Microsoft, Google, Apple, Mozilla, and Opera.\n\nHTML5 In Action provides a complete introduction to web development using HTML5. You'll explore every aspect of the HTML5 specification through real-world examples and code samples. It's much more than just a specification reference, though. It lives up to the name HTML5 in Action by giving you the practical, hands-on guidance you'll need to use key features like:\n\n    * The new semantic elements and form input types\n    * Native multimedia playback with the video and audio elements\n    * Canvas and 2D drawing APIs\n    * Offline applications\n    * Local and session storage, IndexedDB databases\n    * Web workers\n    * Geolocation, File API, History API\n    * Cross-document Message API\n    * Much, much more\n\nWith this book, you can confidently start using HTML5 today. The relevant, easy-to-follow examples will make you a HTML5 master in no time. You'll even learn how to provide fallbacks for browsers that don't support particular HTML5 features.",
		status: 'PUBLISH',
		authors: ['Rob Crowther', 'Joe Lennon', 'Ash Blue', '', 'Greg Wanish'],
		categories: [],
	},
	{
		title: 'Java Persistence with Hibernate, Second Edition',
		isbn: '1617290459',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/bauer3.jpg',
		status: 'MEAP',
		authors: ['Christian Bauer', 'Gavin King', '', 'Gary Gregory'],
		categories: [],
	},
	{
		title: 'Hadoop in Practice',
		isbn: '1617290238',
		pageCount: 0,
		publishedDate: { $date: '2012-10-02T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/holmes.jpg',
		status: 'PUBLISH',
		authors: ['Alex Holmes'],
		categories: [],
	},
	{
		title: 'HBase in Action',
		isbn: '1617290521',
		pageCount: 0,
		publishedDate: { $date: '2012-11-02T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/dimidukkhurana.jpg',
		status: 'PUBLISH',
		authors: ['Nicholas Dimiduk', 'Amandeep Khurana'],
		categories: [],
	},
	{
		title: 'Flex Mobile in Action',
		isbn: '1617290610',
		pageCount: 0,
		publishedDate: { $date: '2012-05-30T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/campos.jpg',
		status: 'PUBLISH',
		authors: ['Jonathan Campos'],
		categories: [],
	},
	{
		title: 'HTML5 for .NET Developers',
		isbn: '1617290432',
		pageCount: 0,
		publishedDate: { $date: '2012-11-30T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/jackson.jpg',
		status: 'PUBLISH',
		authors: ['Jim Jackson', 'II', 'Ian Gilman'],
		categories: [],
	},
	{
		title: '50 Android Hacks',
		isbn: '1617290564',
		pageCount: 0,
		publishedDate: { $date: '2013-06-03T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/sessa.jpg',
		status: 'PUBLISH',
		authors: ['Carlos M. Sessa'],
		categories: [],
	},
	{
		title: 'PowerShell in Depth',
		isbn: '1617290556',
		pageCount: 0,
		publishedDate: { $date: '2013-02-20T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/jones2.jpg',
		status: 'PUBLISH',
		authors: ['Don Jones', 'Richard Siddaway', '', 'Jeffery Hicks'],
		categories: [],
	},
	{
		title: 'Augmented Reality Revealed',
		isbn: '1617290165',
		pageCount: 0,
		status: 'MEAP',
		authors: ['Robert A. Rice Jr.'],
		categories: [],
	},
	{
		title: 'Building Well-Structured JavaScript Applications',
		isbn: '1617290599',
		pageCount: 0,
		status: 'MEAP',
		authors: ['Julio C. Ody'],
		categories: [],
	},
	{
		title: 'Linked Data',
		isbn: '1617290394',
		pageCount: 0,
		publishedDate: { $date: '2013-12-31T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/dwood.jpg',
		status: 'PUBLISH',
		authors: [
			'David Wood',
			'Marsha Zaidman',
			'Luke Ruth',
			'with Michael Hausenblas',
		],
		categories: [],
	},
	{
		title: 'Mule in Action, Second Edition',
		isbn: '1617290823',
		pageCount: 0,
		publishedDate: { $date: '2014-02-20T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/dossot2.jpg',
		status: 'PUBLISH',
		authors: ['David Dossot', "John D'Emic", '', 'Victor Romero'],
		categories: [],
	},
	{
		title: 'Single Page Web Applications',
		isbn: '1617290750',
		pageCount: 0,
		publishedDate: { $date: '2013-09-19T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/mikowski.jpg',
		status: 'PUBLISH',
		authors: ['Michael S. Mikowski', 'Josh C. Powell'],
		categories: [],
	},
	{
		title: 'The Art of Unit Testing, Second Edition',
		isbn: '1617290890',
		pageCount: 0,
		publishedDate: { $date: '2013-11-25T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/osherove2.jpg',
		status: 'PUBLISH',
		authors: ['Roy Osherove'],
		categories: [],
	},
	{
		title: 'Play for Java',
		isbn: '1617290904',
		pageCount: 0,
		publishedDate: { $date: '2014-03-14T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/leroux.jpg',
		status: 'PUBLISH',
		authors: ['Nicolas Leroux', 'Sietse de Kaper'],
		categories: [],
	},
	{
		title: 'Hello World! Second Edition',
		isbn: '1617290920',
		pageCount: 0,
		publishedDate: { $date: '2013-12-12T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/sande2.jpg',
		status: 'PUBLISH',
		authors: ['Warren Sande', 'Carter Sande'],
		categories: [],
	},
	{
		title: 'Dart in Action',
		isbn: '1617290866',
		pageCount: 0,
		publishedDate: { $date: '2012-12-31T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/buckett.jpg',
		status: 'PUBLISH',
		authors: ['Chris Buckett'],
		categories: [],
	},
	{
		title: 'Redis in Action',
		isbn: '1617290858',
		pageCount: 0,
		publishedDate: { $date: '2013-06-18T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/carlson.jpg',
		status: 'PUBLISH',
		authors: ['Josiah Carlson'],
		categories: [],
	},
	{
		title: 'Using the TI-83 Plus/TI-84 Plus',
		isbn: '161729084X',
		pageCount: 0,
		publishedDate: { $date: '2013-08-19T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/mitchell2.jpg',
		status: 'PUBLISH',
		authors: ['Christopher R. Mitchell'],
		categories: [],
	},
	{
		title: 'Neo4j in Action',
		isbn: '1617290769',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/partner.jpg',
		status: 'MEAP',
		authors: ['Jonas Partner', 'Aleksa Vukotic', '', 'Nicki Watt'],
		categories: [],
	},
	{
		title: 'Programming the TI-83 Plus/TI-84 Plus',
		isbn: '1617290777',
		pageCount: 0,
		publishedDate: { $date: '2012-09-14T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/mitchell.jpg',
		status: 'PUBLISH',
		authors: ['Christopher R. Mitchell'],
		categories: [],
	},
	{
		title: 'Functional Programming in Scala',
		isbn: '1617290653',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/bjarnason.jpg',
		status: 'MEAP',
		authors: ['Paul Chiusano', 'Rúnar Bjarnason'],
		categories: [],
	},
	{
		title: 'Play for Scala',
		isbn: '1617290793',
		pageCount: 0,
		publishedDate: { $date: '2013-10-03T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/hilton.jpg',
		status: 'PUBLISH',
		authors: ['Peter Hilton', 'Erik Bakker', '', 'Francisco Canedo'],
		categories: [],
	},
	{
		title: 'Node.js in Practice',
		isbn: '1617290939',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/templier2.jpg',
		status: 'MEAP',
		authors: ['Alex Young', 'Marc Harter'],
		categories: [],
	},
	{
		title: 'SonarQube in Action',
		isbn: '1617290955',
		pageCount: 0,
		publishedDate: { $date: '2013-10-30T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/papapetrou.jpg',
		status: 'PUBLISH',
		authors: ['G. Ann Campbell', 'Patroklos P. Papapetrou'],
		categories: [],
	},
	{
		title: 'Windows Store App Development: C# and XAML',
		isbn: '1617290947',
		pageCount: 0,
		publishedDate: { $date: '2013-06-03T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/pbrown3.jpg',
		status: 'PUBLISH',
		authors: ['Peter M. Brown'],
		categories: [],
	},
	{
		title: 'Learn Windows IIS in a Month of Lunches',
		isbn: '1617290971',
		pageCount: 0,
		publishedDate: { $date: '2013-12-31T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/helmick.jpg',
		status: 'PUBLISH',
		authors: ['Jason C. Helmick'],
		categories: [],
	},
	{
		title: 'Mondrian in Action',
		isbn: '161729098X',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/back.jpg',
		status: 'PUBLISH',
		authors: ['William Back', 'Nicholas Goodman', '', 'Julian Hyde'],
		categories: [],
	},
	{
		title: 'RabbitMQ in Depth',
		isbn: '1617291005',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/roy.jpg',
		status: 'MEAP',
		authors: ['Gavin M. Roy'],
		categories: [],
	},
	{
		title: 'Akka in Action',
		isbn: '1617291013',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/roestenburg.jpg',
		status: 'MEAP',
		authors: [
			'Raymond Roestenburg',
			'Rob Bakker',
			'Rob Williams',
			'Steven Haines',
		],
		categories: [],
	},
	{
		title: 'Extending jQuery',
		isbn: '161729103X',
		pageCount: 0,
		publishedDate: { $date: '2013-08-12T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/wood.jpg',
		status: 'PUBLISH',
		authors: ['Keith B. Wood'],
		categories: [],
	},
	{
		title: 'OCA Java SE 7 Programmer I Certification Guide',
		isbn: '1617291048',
		pageCount: 0,
		publishedDate: { $date: '2013-04-02T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/gupta.jpg',
		status: 'PUBLISH',
		authors: ['Mala Gupta'],
		categories: [],
	},
	{
		title: 'Kanban in Action',
		isbn: '1617291056',
		pageCount: 0,
		publishedDate: { $date: '2014-03-04T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/hammarberg.jpg',
		status: 'PUBLISH',
		authors: ['Marcus Hammarberg', 'Joakim Sunden'],
		categories: [],
	},
	{
		title: 'Solr in Action',
		isbn: '1617291021',
		pageCount: 0,
		publishedDate: { $date: '2014-03-25T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/grainger.jpg',
		status: 'PUBLISH',
		authors: ['Trey Grainger', 'Timothy Potter'],
		categories: [],
	},
	{
		title: 'Making Sense of NoSQL',
		isbn: '1617291072',
		pageCount: 0,
		publishedDate: { $date: '2013-09-03T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/mccreary.jpg',
		status: 'PUBLISH',
		authors: ['Daniel G. McCreary', 'Ann M. Kelly'],
		categories: [],
	},
	{
		title: 'Jaguar Development with PowerBuilder 7',
		isbn: '1884777864',
		pageCount: 0,
		publishedDate: { $date: '1999-08-09T00:00:00.000-0700' },
		status: 'PUBLISH',
		authors: ['MIchael Barlotta'],
		categories: [],
	},
	{
		title: 'Grails in Action, Second Edition',
		isbn: '1617290963',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/gsmith2.jpg',
		status: 'MEAP',
		authors: ['Glen Smith', 'Peter Ledbrook'],
		categories: [],
	},
	{
		title: 'Rails 4 in Action',
		isbn: '1617291099',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/bigg2.jpg',
		status: 'MEAP',
		authors: ['Ryan Bigg', 'Yehuda Katz', 'and Steve Klabnik', ''],
		categories: [],
	},
	{
		title: 'Learn Windows PowerShell in a Month of Lunches, Second Edition',
		isbn: '1617291080',
		pageCount: 0,
		publishedDate: { $date: '2012-11-12T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/jones3.jpg',
		status: 'PUBLISH',
		authors: ['Don Jones', 'Jeffery D. Hicks'],
		categories: [],
	},
	{
		title: 'AOP in .NET',
		isbn: '1617291145',
		pageCount: 0,
		publishedDate: { $date: '2013-06-21T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/groves.jpg',
		status: 'PUBLISH',
		authors: ['Matthew D. Groves'],
		categories: [],
	},
	{
		title: 'Learn PowerShell Toolmaking in a Month of Lunches',
		isbn: '1617291161',
		pageCount: 0,
		publishedDate: { $date: '2012-12-12T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/jones4.jpg',
		status: 'PUBLISH',
		authors: ['Don Jones', 'Jeffery Hicks'],
		categories: [],
	},
	{
		title: 'CMIS and Apache Chemistry in Action',
		isbn: '1617291153',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/mueller.jpg',
		status: 'PUBLISH',
		authors: ['Florian Müller', 'Jay Brown', 'Jeff Potts'],
		categories: [],
	},
	{
		title: 'Action Guide (aka VB .NET)',
		isbn: '1930110324',
		pageCount: 0,
		status: 'PUBLISH',
		authors: ['Paul Messick'],
		categories: [],
	},
	{
		title: 'Learn Active Directory Management in a Month of Lunches',
		isbn: '1617291196',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/siddaway3.jpg',
		status: 'PUBLISH',
		authors: ['Richard Siddaway'],
		categories: [],
	},
	{
		title: 'Spring in Action, Fourth Edition',
		isbn: '161729120X',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/walls5.jpg',
		status: 'MEAP',
		authors: ['Craig Walls'],
		categories: [],
	},
	{
		title: 'The Mikado Method',
		isbn: '1617291218',
		pageCount: 0,
		publishedDate: { $date: '2014-03-05T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/ellnestam.jpg',
		status: 'PUBLISH',
		authors: ['Ola Ellnestam', 'Daniel Brolund'],
		categories: [],
	},
	{
		title: 'The Responsive Web',
		isbn: '1617291242',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/carver.jpg',
		status: 'MEAP',
		authors: ['Matthew Carver'],
		categories: [],
	},
	{
		title: 'Fast ASP.NET Websites',
		isbn: '1617291250',
		pageCount: 0,
		publishedDate: { $date: '2013-08-29T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/hume.jpg',
		status: 'PUBLISH',
		authors: ['Dean Alan Hume'],
		categories: [],
	},
	{
		title: 'SBT in Action',
		isbn: '1617291277',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/suereth2.jpg',
		status: 'MEAP',
		authors: ['Joshua Suereth', 'Matthew Farwell'],
		categories: [],
	},
	{
		title: 'PowerShell Deep Dives',
		isbn: '1617291315',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/hicks.jpg',
		status: 'PUBLISH',
		authors: [
			'Edited by Jeffery Hicks',
			'Richard Siddaway',
			'Oisin Grehan',
			'',
			'Aleksandar Nikolic',
		],
		categories: [],
	},
	{
		title: 'Gradle in Action',
		isbn: '1617291307',
		pageCount: 0,
		publishedDate: { $date: '2014-02-18T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/muschko.jpg',
		status: 'PUBLISH',
		authors: ['Benjamin Muschko'],
		categories: [],
	},
	{
		title: 'Scalatra in Action',
		isbn: '1617291293',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/carrero2.jpg',
		status: 'MEAP',
		authors: [
			'Ivan Porto Carrero',
			'Ross A. Baker',
			'Dave Hrycyszyn',
			'Stefan Ollinger',
			'',
			'Jared Armstrong',
		],
		categories: [],
	},
	{
		title: 'AngularJS in Action',
		isbn: '1617291331',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/bford.jpg',
		status: 'MEAP',
		authors: ['Brian Ford', 'Lukas Ruebbelke'],
		categories: [],
	},
	{
		title: 'Software Development Metrics',
		isbn: '1617291358',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/nicolette.jpg',
		status: 'MEAP',
		authors: ['David Nicolette'],
		categories: [],
	},
	{
		title: 'F# Deep Dives',
		isbn: '1617291323',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/petricek_trelford.jpg',
		status: 'MEAP',
		authors: ['Tomas Petricek', 'Phillip Trelford'],
		categories: [],
	},
	{
		title: 'C# in Depth, Third Edition',
		isbn: '161729134X',
		pageCount: 0,
		publishedDate: { $date: '2013-09-19T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/skeet3.jpg',
		status: 'PUBLISH',
		authors: ['Jon Skeet'],
		categories: [],
	},
	{
		title: 'PostGIS in Action, Second Edition',
		isbn: '1617291390',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/obe2.jpg',
		status: 'MEAP',
		authors: ['Regina Obe', 'Leo Hsu'],
		categories: [],
	},
	{
		title: 'R in Action, Second Edition',
		isbn: '1617291382',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/kabacoff2.jpg',
		status: 'MEAP',
		authors: ['Robert Kabacoff'],
		categories: [],
	},
	{
		title: 'The Joy of Clojure, Second Edition',
		isbn: '1617291412',
		pageCount: 0,
		publishedDate: { $date: '2014-05-29T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/fogus2.jpg',
		status: 'PUBLISH',
		authors: ['Michael Fogus', 'Chris Houser'],
		categories: [],
	},
	{
		title: 'iOS 7 in Action',
		isbn: '1617291420',
		pageCount: 0,
		publishedDate: { $date: '2014-04-03T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/lim2.jpg',
		status: 'PUBLISH',
		authors: ['Brendan G. Lim', 'Martin Conte Mac Donell'],
		categories: [],
	},
	{
		title: 'Hello App Inventor!',
		isbn: '1617291439',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/beer.jpg',
		status: 'MEAP',
		authors: ['Paula Beer', 'Carl Simmons'],
		categories: [],
	},
	{
		title: 'Ember.js in Action',
		isbn: '1617291455',
		pageCount: 0,
		publishedDate: { $date: '2014-06-10T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/skeie.jpg',
		status: 'PUBLISH',
		authors: ['Joachim Haagen Skeie'],
		categories: [],
	},
	{
		title: 'Netty in Action',
		isbn: '1617291471',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/maurer.jpg',
		status: 'MEAP',
		authors: ['Norman Maurer', 'Courtney Robinson'],
		categories: [],
	},
	{
		title: 'RavenDB in Action',
		isbn: '1617291501',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/syn-hershko.jpg',
		status: 'MEAP',
		authors: ['Itamar Syn-Hershko'],
		categories: [],
	},
	{
		title: 'OCP Java SE 7 Programmer II Certification Guide',
		isbn: '161729148X',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/gupta2.jpg',
		status: 'MEAP',
		authors: ['Mala Gupta'],
		categories: [],
	},
	{
		title: 'Backbone.js in Action',
		isbn: '1617291536',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/breed.jpg',
		status: 'MEAP',
		authors: [
			'Samuel M. Breed',
			'Cole Krumbholz',
			'',
			'Phillip Whisenhunt',
		],
		categories: [],
	},
	{
		title: 'Clojure in Action, Second Edition',
		isbn: '1617291528',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/rathore2.jpg',
		status: 'MEAP',
		authors: ['Amit Rathore'],
		categories: [],
	},
	{
		title: 'Practical Data Science with R',
		isbn: '1617291560',
		pageCount: 0,
		publishedDate: { $date: '2014-04-02T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/zumel.jpg',
		status: 'PUBLISH',
		authors: ['Nina Zumel', 'John Mount'],
		categories: [],
	},
	{
		title: 'ArcGIS Web Development',
		isbn: '1617291617',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/rubalcava.jpg',
		status: 'MEAP',
		authors: ['Rene Rubalcava'],
		categories: [],
	},
	{
		title: 'Elasticsearch in Action',
		isbn: '1617291625',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/hinman.jpg',
		status: 'MEAP',
		authors: ['Radu Gheorghe', 'Matthew Lee Hinman'],
		categories: [],
	},
	{
		title: 'Learn SCCM 2012 in a Month of Lunches',
		isbn: '1617291684',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/bannan.jpg',
		status: 'MEAP',
		authors: ['James Bannan'],
		categories: [],
	},
	{
		title: 'Programming for Musicians and Digital Artists',
		isbn: '1617291706',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/kapur.jpg',
		status: 'MEAP',
		authors: ['Ajay Kapur', 'Perry Cook', 'Spencer Salazar', '', 'Ge Wang'],
		categories: [],
	},
	{
		title: 'BDD in Action',
		isbn: '161729165X',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/smart.jpg',
		status: 'MEAP',
		authors: ['John F. Smart'],
		categories: [],
	},
	{
		title: 'Windows Phone 8 in Action',
		isbn: '1617291374',
		pageCount: 0,
		publishedDate: { $date: '2013-12-31T00:00:00.000-0800' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/binkley.jpg',
		status: 'PUBLISH',
		authors: [
			'Timothy Binkley-Jones',
			'Massimo Perga',
			'Michael Sync',
			'Adam Benoit',
		],
		categories: [],
	},
	{
		title: 'Titanium Alloy in Action',
		isbn: '1617291749',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/alcocer.jpg',
		status: 'MEAP',
		authors: ['Ricardo Alcocer'],
		categories: [],
	},
	{
		title: 'Giraph in Action',
		isbn: '1617291757',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/martella.jpg',
		status: 'MEAP',
		authors: [
			'Claudio Martella',
			'Roman Shaposhnik',
			'',
			'Dionysios Logothetis',
		],
		categories: [],
	},
	{
		title: 'The Well-Grounded Rubyist, Second Edition',
		isbn: '1617291692',
		pageCount: 0,
		publishedDate: { $date: '2014-06-24T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/black3.jpg',
		status: 'PUBLISH',
		authors: ['David A. Black'],
		categories: [],
	},
	{
		title: 'Go in Action',
		isbn: '1617291781',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/ketelsen.jpg',
		status: 'MEAP',
		authors: ['Brian Ketelsen', 'Erik St. Martin', '', 'William Kennedy'],
		categories: [],
	},
	{
		title: "The Programmer's Guide to Apache Thrift ",
		isbn: '1617291811',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/abernethy.jpg',
		status: 'MEAP',
		authors: ['Randy Abernethy'],
		categories: [],
	},
	{
		title: 'Grokking Functional Programming',
		isbn: '1617291838',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/khan.jpg',
		status: 'MEAP',
		authors: ['Aslam Khan'],
		categories: [],
	},
	{
		title: 'CORS in Action',
		isbn: '161729182X',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/hossain.jpg',
		status: 'MEAP',
		authors: ['Monsur Hossain'],
		categories: [],
	},
	{
		title: 'Reactive Design Patterns',
		isbn: '1617291803',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/kuhn.jpg',
		status: 'MEAP',
		authors: ['Roland Kuhn', 'Jamie Allen'],
		categories: [],
	},
	{
		title: 'Storm Applied',
		isbn: '1617291897',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/pathirana.jpg',
		status: 'MEAP',
		authors: ['Sean Allen', 'Peter Pathirana', '', 'Matthew Jankowski'],
		categories: [],
	},
	{
		title: 'Real-World Machine Learning',
		isbn: '1617291927',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/brink.jpg',
		status: 'MEAP',
		authors: ['Henrik Brink', 'Joseph Richards'],
		categories: [],
	},
	{
		title: 'jQuery UI in Action',
		isbn: '1617291935',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/vantoll.jpg',
		status: 'MEAP',
		authors: ['Theodore J. (T.J.) VanToll III'],
		categories: [],
	},
	{
		title: 'Web Components in Action',
		isbn: '1617291943',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/buckett2.jpg',
		status: 'MEAP',
		authors: ['Chris Buckett'],
		categories: [],
	},
	{
		title: 'JavaScript Application Design',
		isbn: '1617291951',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/bevacqua.jpg',
		status: 'MEAP',
		authors: ['Nicolas G. Bevacqua'],
		categories: [],
	},
	{
		title: 'Git in Practice',
		isbn: '1617291978',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/mcquaid.jpg',
		status: 'MEAP',
		authors: ['Mike McQuaid'],
		categories: [],
	},
	{
		title: 'Impala in Action',
		isbn: '1617291986',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/saltzer.jpg',
		status: 'MEAP',
		authors: ['Richard L. Saltzer', 'Istvan Szegedi'],
		categories: [],
	},
	{
		title: 'Java 8 in Action',
		isbn: '1617291994',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/urma.jpg',
		status: 'MEAP',
		authors: ['Raoul-Gabriel Urma', 'Mario Fusco', '', 'Alan Mycroft'],
		categories: [],
	},
	{
		title: 'Elixir in Action',
		isbn: '161729201X',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/juric.jpg',
		status: 'MEAP',
		authors: ['Saša Juric´'],
		categories: [],
	},
	{
		title: 'MongoDB in Action, Second Edition',
		isbn: '1617291609',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/banker2.jpg',
		status: 'MEAP',
		authors: [
			'Kyle Banker',
			'Peter Bakkum',
			'Tim Hawkins',
			'Shaun Verch',
			'',
			'Douglas Garrett',
		],
		categories: [],
	},
	{
		title: 'Getting MEAN with Mongo, Express, Angular, and Node',
		isbn: '1617292036',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/sholmes.jpg',
		status: 'MEAP',
		authors: ['Simon Holmes'],
		categories: [],
	},
	{
		title: 'jQuery in Action, Third Edition',
		isbn: '1617292079',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/derosa.jpg',
		status: 'MEAP',
		authors: ['Bear Bibeault', 'Yehuda Katz', '', 'Aurelio De Rosa'],
		categories: [],
	},
	{
		title: 'D3.js in Action',
		isbn: '1617292117',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/meeks.jpg',
		status: 'MEAP',
		authors: ['Elijah Meeks'],
		categories: [],
	},
	{
		title: 'Learn SQL Server Administration in a Month of Lunches',
		isbn: '1617292133',
		pageCount: 0,
		publishedDate: { $date: '2014-05-02T00:00:00.000-0700' },
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/jones5.jpg',
		status: 'PUBLISH',
		authors: ['Don Jones'],
		categories: [],
	},
	{
		title: 'Geoprocessing with Python',
		isbn: '1617292141',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/garrard.jpg',
		status: 'MEAP',
		authors: ['Chris Garrard'],
		categories: [],
	},
	{
		title: 'Barcodes with iOS',
		isbn: '161729215X',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/drobnik.jpg',
		status: 'MEAP',
		authors: ['Oliver Drobnik'],
		categories: [],
	},
	{
		title: 'Chef in Action',
		isbn: '1617292214',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/aivaliotis.jpg',
		status: 'MEAP',
		authors: ['Dimitri Aivaliotis'],
		categories: [],
	},
	{
		title: 'Hadoop in Practice, Second Edition',
		isbn: '1617292222',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/holmes2.jpg',
		status: 'MEAP',
		authors: ['Alex Holmes'],
		categories: [],
	},
	{
		title: 'Oculus Rift in Action',
		isbn: '1617292192',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/bdavis.jpg',
		status: 'MEAP',
		authors: ['Bradley Austin Davis', 'Karen Bryla', '', 'Alex Benton'],
		categories: [],
	},
	{
		title: 'OpenStack in Action',
		isbn: '1617292168',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/bumgardner.jpg',
		status: 'MEAP',
		authors: ['Cody Bumgardner'],
		categories: [],
	},
	{
		title: 'PowerShell in Depth, Second Edition',
		isbn: '1617292184',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/jones6.jpg',
		status: 'MEAP',
		authors: ['Don Jones', 'Jeffery Hicks', '', 'Richard Siddaway'],
		categories: [],
	},
	{
		title: 'Practical Probabilistic Programming',
		isbn: '1617292338',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/pfeffer.jpg',
		status: 'MEAP',
		authors: ['Avi Pfeffer'],
		categories: [],
	},
	{
		title: 'Unity in Action',
		isbn: '161729232X',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/hocking.jpg',
		status: 'MEAP',
		authors: ['Joseph Hocking'],
		categories: [],
	},
	{
		title: 'Express.js in Action',
		isbn: '1617292427',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/hahn.jpg',
		status: 'MEAP',
		authors: ['Evan M. Hahn'],
		categories: [],
	},
	{
		title: 'Learn Git in a Month of Lunches',
		isbn: '1617292419',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/umali.jpg',
		status: 'MEAP',
		authors: ['Rick Umali'],
		categories: [],
	},
	{
		title: 'Understanding SPAs',
		isbn: '1617292435',
		pageCount: 0,
		thumbnailUrl:
			'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/scott2.jpg',
		status: 'MEAP',
		authors: ['Emmit A. Scott', 'Jr.'],
		categories: [],
	},
]
